services:
  is-django:
    ports:
      - "8000:8000"
    command:
      [
        "sh",
        "-c",
        "python3 -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:8000",
        "uvicorn",
        "randouyin.drivers.web.main:app",
        "--host",
        "0.0.0.0",
        "--workers",
        "4",
        "--reload",
      ]
