services:
  web:
    container_name: rand-web
    hostname: randouyin
    build:
      context: .
      dockerfile: ./Dockerfile.pw
    restart: on-failure
    init: true
    ipc: host
    shm_size: 1g
    security_opt:
      - seccomp=./seccomp_profile.json
    cap_add:
      - SYS_ADMIN
    extra_hosts:
      - "hostmachine:host-gateway"
    ports:
      - "8000:8000"
    volumes:
      - ./randouyin:/app/randouyin
    networks:
      - randouyin-network

networks:
  randouyin-network:
    driver: bridge
